images:
  tezosFaucet: ghcr.io/oxheadalpha/tezos-faucet:2.0.0
  tezosFaucetBackend: ghcr.io/oxheadalpha/tezos-faucet-backend:2.0.0

# Value the server sets for the "Access-Control-Allow-Origin" header for CORS.
authorizedHost: "" # filled in by pulumi
# RPC url for the faucet backend. Default value assumes tezos-k8s created an RPC
# service in the same namespace. If not set, defaults to `config.network.rpcUrl`.
backendRpcUrl: http://tezos-node-rpc:8732
# If the backend requires CAPTCHA tokens to be submitted.
enableCaptcha: true
# Faucet won't dispense to an address if its balance exceeds this.
maxBalance: 61000

config:
  application:
    name: "Tezos Oxfordnet Faucet"
    googleCaptchaSiteKey: #filled in by pulumi
    backendUrl: # filled in by pulumi
    githubRepo: "https://github.com/oxheadalpha/tezos-faucet"
  network:
    name: custom # Beacon SDK doesn't recognize Oxfordnet atm.
    rpcUrl: # filled in by pulumi
    faucetAddress: tz1a4GT7THHaGDiTxgXoatDWcZfJ5j29z5RC
    viewer: https://oxford.tzstats.com

profiles:
  user:
    amount: 100
  baker:
    amount: 6001

disableChallenges: false
redis:
  url: "redis://redis-master:6379"

ingress:
  enabled: true
  annotations:
    "kubernetes.io/ingress.class": "nginx"
    "cert-manager.io/cluster-issuer": "letsencrypt-prod"
  host: "" # faucet fqdn, filled in by pulumi
  tls: [] # filled in by pulumi
