accounts:
  oxheadbaker:
    # tz1foXHgRzdYdaLgX6XhpZGxbBv42LZ6ubvE
    bootstrap_balance: "9700000000000"
    is_bootstrap_baker_account: true
    # key injected by pulumi
  oxheadfree:
    # an account with a lot of money in it
    # tz1foxFdz2ieSj8P9YxKYBTEqYbgFXXEeiQY
    key: edpkubSgCoMjB2a6vPWRNRHfGa6HUFfFyEUKoEQhWC8osnav8QzBdJ
    bootstrap_balance: "50000000000000000"
    is_bootstrap_baker_account: false
  bakingbadfaucet:
    # baking bad maintains a telegram faucet bot
    # tz1KhnTgwoRRALBX6vRHRnydDGSBFsWtcJxc
    key: edpkuFRauFAdhipQu9s4xmfNJWmtLxPKpoaoG41gYGq5AgUA43Vxqx
    is_bootstrap_baker_account: false
    bootstrap_balance: "5000000000000000"
  tz1THUNA:
    # tz1THUNARo58aD5YdNGYPnWNnvd8yHPrMdsF
    # Romain's faucet
    key: edpkuh3WSwziyd6nXqDXeh48vZHp5ETxFd43EdkbzhmW98BvuLXK81
    is_bootstrap_baker_account: false
    bootstrap_balance: "50000000000000000"
  foundationfaucet:
    # TF funds to deploy more bakers later if needed
    # chris.pinnock@tezos.foundation
    # tz1LwEoAHSxsMm8dECaQTGNsGvXCD9HeBgdj
    key: edpku2v3DA5WFGE7LSjNVC8FTVhy2LdSu8U34GYaT1zfzZaugCbpVU
    is_bootstrap_baker_account: false
    bootstrap_balance: "50000000000000000"
  oxheadfaucet:
    # the faucet on teztnets platform
    # tz1a4GT7THHaGDiTxgXoatDWcZfJ5j29z5RC
    key: edpkvGYHoY5kwq13Ak6r4fLa1GGSHKJZVe7xJFV6ZgHwdZeaHy3WZj
    is_bootstrap_baker_account: false
    bootstrap_balance: "15000000000000"
  tf:
    # tz3Q1fwk1vh3zm5LqyUV9e2wZBdaEXcovh2r
    key: p2pk66p7iVbEFyJaYM5bjJmXP74B7qso8rXMCmKwVRdRZunMdhUjYBH
    is_bootstrap_baker_account: true
    bootstrap_balance: "1000000000000"
  marco:
    # Marco Schurtenberger
    key: edpkubw32gvTfUYRERGECHbMTsiLdM9z9JrEXGVEahbZf9yMhTozSg
    is_bootstrap_baker_account: true
    bootstrap_balance: "1000000000000"
  andrewk:
    # tz1aWXP237BLwNHJcCD4b3DutCevhqq2T1Z9
    key: edpkvNGUd3xcBNmPWRbXJoS6WEvxu1BVoWjHr7ab7QoAJFFqhx9tkR
    is_bootstrap_baker_account: true
    bootstrap_balance: "1000000000000"
  pirbo:
    # tz1PirbogVqfmBT9XCuYJ1KnDx4bnMSYfGru
    key: edpkvaQpRgsSGPJSY91sjNArLMgpTUHmmfkvuSekwos43uze2H2EFM
    is_bootstrap_baker_account: true
    bootstrap_balance: "1000000000000"
  ecadlabs:
    # tz1cjyja1TU6fiyiFav3mFAdnDsCReJ12hPD
    key: edpkvP1NXoo8vhYbPSvXdy466EHoYWBpf6zmjghB2p3DwJPjbB5nsf
    is_bootstrap_baker_account: true
    bootstrap_balance: "1000000000000"
  ecadlabs_2:
    # tz1RuHDSj9P7mNNhfKxsyLGRDahTX5QD1DdP
    key: edpkthQu5xeKjD9Dxh5tAf3f61z2Nteqk9xRVPVoZekk1CF738zbcJ
    is_bootstrap_baker_account: true
    bootstrap_balance: "1000000000000"
  # fredcy:
  #   # tz1KkJtLB9pMdLKNpVRNZw9zmysrxKmYcRGU
  #   key: edpkvTUqzRYhotk2YFnemLfBk8apvcSVNwTSxB6F6CaXUA64CRXgHN
  #   is_bootstrap_baker_account: true
  #   bootstrap_balance: "1000000000000"
  # pasqualepinto:
  #   # tz1hoyMUiJYYr4FRPMU8Z7WJzYkqgjygjaTy
  #   key: edpkugfNCoDerYV9pq1EfGgjX9mPk3uxX2wXhRz85dUNMtTUPnhjJE
  #   is_bootstrap_baker_account: true
  #   bootstrap_balance: "1000000000000"b
  rich:
    # Richard Ayotte (https://twitter.com/RichAyotte or anarcode)
    # tz1MDBXbMoLwTjeGYUckSWSTKp5kznTstafr
    key: edpkuK9vRbs1ZKLkaPHdKQ3L4h1YbDUFAt4PHT7MXRDqGpRLLBy6v8
    is_bootstrap_baker_account: true
    bootstrap_balance: "1000000000000"
  vincent_xtzmaster:
    # tz1M9b1sKoh5GB7AiBiqdMrjMMyvuhsZua5n
    key: edpktrpiJF24hcmJ22tfDaFWuFihZYbSgr15vFAGUmHThtnr37BZqX
    is_bootstrap_baker_account: true
    bootstrap_balance: "1000000000000"
  killian_d:
    # tz1gBnaS1n7LKqpaRnyBX5MSmamadXXfzNpt
    key: edpkv7AqKLxQXWa2tHcPbMnah1JbMUHohvmvgPS7nVaB7kdNnrg1XW
    is_bootstrap_baker_account: true
    bootstrap_balance: "1000000000000"
  # feeny:
  #   key: edpktmqPi9eRefM9ZrwsPNAdg9832UDg3r894J4rkBGfUhpqZpqx6y
  #   is_bootstrap_baker_account: true
  #   bootstrap_balance: "1000000000000"
  albin:
    # tz1YtB3Hn6oghVk96vkpZt6PHrfbyRY1ciL3
    key: edpkuc4NCkkmTyLogcU32b7sU363J2jggs19EyBzhmms6JmjQZxEJo
    is_bootstrap_baker_account: true
    bootstrap_balance: "1000000000000"
  # blueledger:
  #   # Mike Kerhnaghan
  #   # tz1bQYMFieZHomNPjJvpp2g7PuhxRPDxpnFt
  #   key: edpkvMWcnT7ha4m9kDv82X11Yx39xyowquUdBKpne5tpUyajcbjH6L
  #   is_bootstrap_baker_account: true
  #   bootstrap_balance: "1000000000000"

node_config_network:
  activation_account_name: oxheadbaker
  chain_name: TEZOS_OXFORDNET_2023-08-21T15:00:00Z
  genesis:
    protocol: Ps9mPmXaRzmzk35gbAYNCAw6UXdE2qoABTHbN2oEEc1qM7CwT9P
    timestamp: "2023-08-21T15:00:00Z"

activation:
  protocol_hash: PtNairobiyssHuh87hEhfVBGCVrK3WnS8Z2FT4ymB5tAa4r1nQf
  protocol_parameters:
    preserved_cycles: 3
    blocks_per_cycle: 8192
    blocks_per_commitment: 64
    blocks_per_stake_snapshot: 512
    cycles_per_voting_period: 1
    hard_gas_limit_per_operation: '1040000'
    hard_gas_limit_per_block: '2600000'
    proof_of_work_threshold: '-1'
    minimal_stake: '6000000000'
    seed_nonce_revelation_tip: '125000'
    baking_reward_fixed_portion: '2666666'
    baking_reward_bonus_per_slot: '1143'
    endorsing_reward_per_slot: '761'
    hard_storage_limit_per_operation: '60000'
    origination_size: 257
    cost_per_byte: '250'
    quorum_max: 7000
    quorum_min: 2000
    min_proposal_quorum: 500
    liquidity_baking_subsidy: '666666'
    liquidity_baking_toggle_ema_threshold: 1000000000
    max_operations_time_to_live: 240
    minimal_block_delay: "8"
    delay_increment_per_round: "3"
    consensus_committee_size: 7000
    consensus_threshold: 4667
    minimal_participation_ratio:
      numerator: 2
      denominator: 3
    max_slashing_period: 2
    frozen_deposits_percentage: 10
    double_baking_punishment: "640000000"
    ratio_of_frozen_deposits_slashed_per_double_endorsement:
      numerator: 1
      denominator: 2
    cache_script_size: 100000000
    cache_stake_distribution_cycles: 8
    cache_sampler_state_cycles: 8
    nonce_revelation_threshold: 512
    vdf_difficulty: "10000000000"
    tx_rollup_enable: false
    tx_rollup_origination_size: 4000
    tx_rollup_hard_size_limit_per_inbox: 500000
    tx_rollup_hard_size_limit_per_message: 5000
    tx_rollup_commitment_bond: "10000000000"
    tx_rollup_finality_period: 40000
    tx_rollup_max_inboxes_count: 40100
    tx_rollup_withdraw_period: 40000
    tx_rollup_max_messages_per_inbox: 1010
    tx_rollup_max_commitments_count: 80100
    tx_rollup_cost_per_byte_ema_factor: 120
    tx_rollup_max_withdrawals_per_batch: 15
    tx_rollup_max_ticket_payload_size: 2048
    tx_rollup_rejection_max_proof_size: 30000
    tx_rollup_sunset_level: 10000000
    dal_parametric:
      feature_enable: false
      number_of_slots: 256
      number_of_shards: 2048
      attestation_lag: 1
      attestation_threshold: 50
      slot_size: 1048576
      redundancy_factor: 16
      page_size: 4096
      blocks_per_epoch: 8
    smart_rollup_enable: true
    smart_rollup_origination_size: 6314
    smart_rollup_challenge_window_in_blocks: 40
    smart_rollup_stake_amount: "10000000000"
    smart_rollup_commitment_period_in_blocks: 20
    smart_rollup_max_lookahead_in_blocks: 30000
    smart_rollup_max_active_outbox_levels: 20160
    smart_rollup_max_outbox_messages_per_level: 100
    smart_rollup_number_of_sections_in_dissection: 32
    smart_rollup_timeout_period_in_blocks: 500
    smart_rollup_max_number_of_cemented_commitments: 5
    smart_rollup_max_number_of_parallel_games: 32
    smart_rollup_arith_pvm_enable: false
    zk_rollup_enable: false
    zk_rollup_origination_size: 4000
    zk_rollup_min_pending_to_process: 10
    testnet_dictator: "tz1Xf8zdT3DbAX9cHw3c3CXh79rc4nK4gCe8"

nodes:
  tezos-baking-node:
    instances:
      - bake_using_accounts:
          - oxheadbaker
        config:
          shell:
            history_mode: archive
          rpc:
            cors-headers: [ "content-type" ]
            cors-origin: [ "*" ]
        is_bootstrap_node: true
    runs:
      - octez_node
      - baker
      - accuser
      - vdf
    readiness_probe: false
    storage_size: 160Gi
  # Overwrite default values.yaml rolling-node
  rolling-node: null

full_snapshot_url: null
rolling_snapshot_url: null
rolling_tarball_url: null
archive_tarball_url: null

images:
  octez: tezos/tezos:v18.0-rc1

protocols:
  - command: Proxford
    vote:
      liquidity_baking_toggle_vote: "pass"
      adaptive_issuance_vote: "on"

bootstrap_peers:
  - oxfordnet.tzinit.org
