images:
  tezosFaucet: ghcr.io/oxheadalpha/tezos-faucet:2.2.1
  tezosFaucetBackend: ghcr.io/oxheadalpha/tezos-faucet-backend:2.1.1

# Frontend app configuration. You can optionally deploy only the faucet backend.
enableUI: true
config:
  application:
    name: "Tezos Dailynet faucet"
    googleCaptchaSiteKey: "" #filled in by pulumi
    backendUrl: "" # filled in by pulumi
    githubRepo: https://github.com/oxheadalpha/tezos-faucet
  network:
    name: # filled in by pulumi
    rpcUrl: # filled in by pulumi
    faucetAddress: tz1a4GT7THHaGDiTxgXoatDWcZfJ5j29z5RC
    viewer: https://dailynet.tzstats.com

# Value the server sets for the "Access-Control-Allow-Origin" header for CORS.
authorizedHost: "" # filled in by pulumi
# RPC url for the faucet backend. Default value assumes tezos-k8s created an RPC
# service in the same namespace. If not set, defaults to `config.network.rpcUrl`.
backendRpcUrl: http://tezos-node-rpc:8732
# If the backend requires CAPTCHA tokens to be submitted.
enableCaptcha: true
# Faucet won't dispense to an address if its balance exceeds this.
maxBalance: 1000000
# The minimum Tez allowed per request.
minTez: 1
# The maximum Tez allowed per request.
maxTez: 1000000

disableChallenges: false
# Minimum number of challenges required for the minimum Tez request.
minChallenges: 1
# Maximum number of challenges required for the maximum Tez request.
# 550 challenges should take ~10m.
maxChallenges: 550
# Maximum number of challenges required for the maximum Tez request when a
# captcha is used.
# 26 challenges should take ~2m.
maxChallengesWithCaptcha: 26
# How many bytes the challenge string should be.
challengeSize: 2048
# Difficulty level for challenges.
difficulty: 4

redis:
  url: redis://redis-master:6379

ingress:
  enabled: true
  annotations:
    "kubernetes.io/ingress.class": "nginx"
    "cert-manager.io/cluster-issuer": "letsencrypt-prod"
  host: "" # faucet fqdn, filled in by pulumi
  tls: [] # filled in by pulumi

# Secrets
googleCaptchaSecretKey: "" # filled in by pulumi
faucetPrivateKey: "" # filled in by pulumi
