{
 "title": "Octez DAL Node Dashboard",
 "tags": [
  "tezos",
  "octez",
  "dal"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "node_instance",
    "label": "Node instance",
    "query": "label_values(dal_node_new_layer1_head,pod)"
   },
   { "name": "namespace", "label": "Namespace", "query": "label_values(namespace)" }
  ]
 },
 "panels": [
  { "title": "DAL node's core stats", "type": "row", "gridPos": { "h": 0, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Layer 1 heads & finalized blocks seen by the DAL node",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "dal_node_new_layer1_head{pod=\"$node_instance\"}",
     "legendFormat": "Seen L1 heads"
    },
    {
     "expr": "dal_node_layer1_block_finalized{pod=\"$node_instance\"}",
     "legendFormat": "Finalized L1 blocks"
    }
   ]
  },
  {
   "title": "Rounds of layer 1 heads & finalized blocks seen by the DAL node",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "dal_node_new_layer1_head_round{pod=\"$node_instance\"}",
     "legendFormat": "Seen L1 heads' rounds"
    },
    {
     "expr": "dal_node_layer1_block_finalized_round{pod=\"$node_instance\"}",
     "legendFormat": "Finalized L1 blocks' rounds"
    }
   ]
  },
  {
   "title": "The shards stored by this node (1-minute interval)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "deriv(dal_node_number_of_stored_shards{pod=\"$node_instance\"}[1m])",
     "legendFormat": "Stored shards"
    }
   ]
  },
  {
   "title": "Number of slots waiting for attesatation and of attested slots",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(dal_node_slots_waiting_for_attestaion{pod=\"$node_instance\"})",
     "legendFormat": "Number of slots waiting for attestation"
    },
    {
     "expr": "sum(dal_node_slots_attested{pod=\"$node_instance\"})",
     "legendFormat": "Number of attested slots"
    }
   ]
  },
  {
   "title": "Indexes of slots waiting for attestation",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 9 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "dal_node_slots_waiting_for_attestaion{pod=\"$node_instance\"}",
     "legendFormat": "{{ slot_waiting_for_attestaion }}"
    }
   ]
  },
  {
   "title": "Indexes of attested slots",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 9 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "dal_node_slots_attested{pod=\"$node_instance\"}",
     "legendFormat": "{{ slot_attested }}"
    }
   ]
  },
  { "title": "Gossipsub worker's stats", "type": "row", "gridPos": { "h": 0, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Score of the peers connected to this node",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "dal_gs_scores_of_peers{pod=\"$node_instance\"}",
     "legendFormat": "{{ scores_of_peers }}"
    }
   ]
  },
  {
   "title": "Number of peers in the mesh for each subscribed topic",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "dal_gs_count_peers_per_topic{pod=\"$node_instance\"}",
     "legendFormat": "{{ count_peers_per_topic }}"
    }
   ]
  },
  {
   "title": "The number of topics the node is subscribed to",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "dal_gs_count_topics{pod=\"$node_instance\"}",
     "legendFormat": "Node's topics"
    }
   ]
  },
  {
   "title": "The number of (bootstrap) connections",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 25 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "dal_gs_count_connections{pod=\"$node_instance\"}",
     "legendFormat": "All connections"
    },
    {
     "expr": "dal_gs_count_bootstrap_connections{pod=\"$node_instance\"}",
     "legendFormat": "Bootstrap connections"
    }
   ]
  },
  {
   "title": "The size of different worker streams",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 25 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "dal_gs_input_events_stream_length{pod=\"$node_instance\"}",
     "legendFormat": "Input stream"
    },
    {
     "expr": "dal_gs_p2p_output_stream_length{pod=\"$node_instance\"}",
     "legendFormat": "P2P output stream"
    },
    {
     "expr": "dal_gs_app_output_stream_length{pod=\"$node_instance\"}",
     "legendFormat": "Application output stream"
    }
   ]
  },
  {
   "title": "Average sent & received app messages (1-minute interval)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "deriv(dal_gs_count_received_valid_messages{pod=\"$node_instance\"}[1m])",
     "legendFormat": "Received & valid"
    },
    {
     "expr": "deriv(dal_gs_count_received_invalid_messages{pod=\"$node_instance\"}[1m])",
     "legendFormat": "Received & invalid"
    },
    {
     "expr": "deriv(dal_gs_count_received_unknown_validity_messages{pod=\"$node_instance\"}[1m])",
     "legendFormat": "Received & unchecked validity"
    },
    {
     "expr": "deriv(dal_gs_count_sent_messages{pod=\"$node_instance\"}[1m])",
     "legendFormat": "Sent"
    }
   ]
  },
  {
   "title": "Average sent control & metadata messages (1-minute interval)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 33 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "deriv(dal_gs_count_sent_grafts{pod=\"$node_instance\"}[1m])",
     "legendFormat": "Graft"
    },
    {
     "expr": "deriv(dal_gs_count_sent_prunes{pod=\"$node_instance\"}[1m])",
     "legendFormat": "Prune"
    },
    {
     "expr": "deriv(dal_gs_count_sent_ihaves{pod=\"$node_instance\"}[1m])",
     "legendFormat": "IHave"
    },
    {
     "expr": "deriv(dal_gs_count_sent_iwants{pod=\"$node_instance\"}[1m])",
     "legendFormat": "IWant"
    }
   ]
  },
  {
   "title": "Average received control & metadata messages (1-minute interval)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 33 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "deriv(dal_gs_count_received_grafts{pod=\"$node_instance\"}[1m])",
     "legendFormat": "Graft"
    },
    {
     "expr": "deriv(dal_gs_count_received_prunes{pod=\"$node_instance\"}[1m])",
     "legendFormat": "Prune"
    },
    {
     "expr": "deriv(dal_gs_count_received_ihaves{pod=\"$node_instance\"}[1m])",
     "legendFormat": "IHave"
    },
    {
     "expr": "deriv(dal_gs_count_received_iwants{pod=\"$node_instance\"}[1m])",
     "legendFormat": "IWant"
    }
   ]
  },
  { "title": "P2P stats", "type": "row", "gridPos": { "h": 0, "w": 24, "x": 0, "y": 41 } },
  {
   "title": "Average data exchange (1-minute interval)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "deriv(octez_p2p_io_scheduler_total_recv{pod=\"$node_instance\"}[1m]) / 1000",
     "legendFormat": "Received data (KB)"
    },
    {
     "expr": "deriv(octez_p2p_io_scheduler_total_sent{pod=\"$node_instance\"}[1m]) / 1000",
     "legendFormat": "Sent data (KB)"
    }
   ]
  },
  {
   "title": "P2P total connections",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "octez_p2p_connections_outgoing{pod=\"$node_instance\"}",
     "legendFormat": "Outgoing connections"
    },
    {
     "expr": "octez_p2p_connections_incoming{pod=\"$node_instance\"}",
     "legendFormat": "Incoming connections"
    }
   ]
  },
  {
   "title": "P2P peers connections",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "octez_p2p_peers_disconnected{pod=\"$node_instance\"}",
     "legendFormat": "Disconnected peers"
    },
    {
     "expr": "octez_p2p_peers_running{pod=\"$node_instance\"}",
     "legendFormat": "Running peers"
    },
    {
     "expr": "octez_p2p_points_greylisted{pod=\"$node_instance\"}",
     "legendFormat": "Waiting to reconnect"
    }
   ]
  },
  {
   "title": "P2P points connections",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 49 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "octez_p2p_points_disconnected{pod=\"$node_instance\"}",
     "legendFormat": "Disconnected points"
    },
    {
     "expr": "octez_p2p_points_running{pod=\"$node_instance\"}",
     "legendFormat": "Running points"
    },
    {
     "expr": "octez_p2p_points_trusted{pod=\"$node_instance\"}",
     "legendFormat": "Trusted points"
    }
   ]
  }
 ]
}