apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: tezos-scraper
  namespace: {{ .Release.Namespace }}
  labels:
    release: {{ .Release.Name }}
    nine.ch/prometheus: kube-prometheus-stack
spec:
  namespaceSelector:
    any: true
  selector:
    matchLabels:
      appType: tezos-node
  podMetricsEndpoints:
  - port: tezos-metrics
    interval: 30s
