{
 "title": "Tezos branch: master",
 "tags": [
  "tezos",
  "storage"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(kube_pod_info, namespace)"
    }
   },
   {
    "name": "workload",
    "query": {
     "query": "label_values(kube_pod_info{namespace=~\"$namespace\"}, created_by_name)"
    }
   },
   {
    "name": "pod",
    "query": {
     "query": "label_values(kube_pod_info{namespace=~\"$namespace\",created_by_name=~\"$workload\"}, pod)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Node stats", "type": "row" },
  {
   "title": "Node release version",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "expr": "group(tezos_metrics_info_version{namespace=~\"$namespace\",pod=~\"$workload.*\",pod=~\"$pod\"}) by (version, commit_hash)",
     "legendFormat": "{{ version }}    ::{{ commit_hash }}"
    }
   ]
  },
  {
   "title": "Node uptime",
   "type": "singlestat",
   "description": "Reflects the uptime of the monitoring of the job, not the uptime of the process.",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 3 },
   "format": "dtdhms",
   "valueName": "max",
   "targets": [
    {
     "expr": "avg(time()-(process_start_time_seconds{namespace=~\"$namespace\",pod=~\"$workload.*\",pod=~\"$pod\"}))",
     "legendFormat": "node uptime"
    }
   ]
  },
  {
   "title": "Current head level",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 5 },
   "format": "none",
   "valueName": "max",
   "targets": [
    {
     "expr": "max(tezos_metrics_chain_current_level{namespace=~\"$namespace\",pod=~\"$workload.*\",pod=~\"$pod\"})",
     "legendFormat": "current head level"
    }
   ]
  },
  {
   "title": "Current checkpoint level",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 7 },
   "format": "none",
   "valueName": "max",
   "targets": [
    {
     "expr": "max(tezos_metrics_chain_checkpoint_level{namespace=~\"$namespace\",pod=~\"$workload.*\",pod=~\"$pod\"})",
     "legendFormat": "current checkpoint level"
    }
   ]
  },
  {
   "title": "Current cycle",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 9 },
   "format": "none",
   "valueName": "max",
   "targets": [
    {
     "expr": "max(tezos_metrics_chain_current_cycle{namespace=~\"$namespace\",pod=~\"$workload.*\",pod=~\"$pod\"})",
     "legendFormat": "Current cycle"
    }
   ]
  },
  {
   "title": "Trusted points",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 11 },
   "format": "none",
   "valueName": "max",
   "targets": [
    {
     "expr": "avg(tezos_metrics_p2p_points_trusted{namespace=~\"$namespace\",pod=~\"$workload.*\",pod=~\"$pod\"})",
     "legendFormat": "trusted points"
    }
   ]
  },
  {
   "title": "Private Connections",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 13 },
   "format": "none",
   "valueName": "max",
   "targets": [
    {
     "expr": "avg(tezos_metrics_p2p_connections_private{namespace=~\"$namespace\",pod=~\"$workload.*\",pod=~\"$pod\"})",
     "legendFormat": "Private Connections"
    }
   ]
  },
  {
   "title": "Head level history",
   "type": "graph",
   "gridPos": { "h": 10, "w": 10, "x": 4, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "tezos_metrics_chain_current_level{namespace=~\"$namespace\",pod=~\"$workload.*\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Blocks per second",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 10, "x": 4, "y": 10 },
   "targets": [
    {
     "expr": "rate(tezos_metrics_chain_current_level{namespace=~\"$namespace\",pod=~\"$workload.*\",pod=~\"$pod\"}[5m])",
     "legendFormat": "5 minutes mean"
    }
   ]
  },
  {
   "title": "Node logs",
   "type": "logs",
   "gridPos": { "h": 18, "w": 10, "x": 14, "y": 0 },
   "targets": [
    {
     "expr": "{job=\"varlogs\"}",
     "legendFormat": "Node logs"
    }
   ]
  },
  {
   "title": "Head operations",
   "type": "graph",
   "gridPos": { "h": 8, "w": 14, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "tezos_metrics_chain_head_transaction{namespace=~\"$namespace\",pod=~\"$workload.*\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}}: Transaction"
    },
    {
     "expr": "tezos_metrics_chain_head_double_baking_evidence{namespace=~\"$namespace\",pod=~\"$workload.*\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}}: Double baking evidence"
    },
    {
     "expr": "tezos_metrics_chain_head_delegation{namespace=~\"$namespace\",pod=~\"$workload.*\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}}: delegation"
    },
    {
     "expr": "tezos_metrics_chain_head_ballot{namespace=~\"$namespace\",pod=~\"$workload.*\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}}: ballot"
    },
    {
     "expr": "tezos_metrics_chain_head_double_endorsement_evidence{namespace=~\"$namespace\",pod=~\"$workload.*\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}}: double endorsement evidence"
    },
    {
     "expr": "tezos_metrics_chain_head_origination{namespace=~\"$namespace\",pod=~\"$workload.*\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}}: origination"
    },
    {
     "expr": "tezos_metrics_chain_head_proposals{namespace=~\"$namespace\",pod=~\"$workload.*\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}}: proposals"
    },
    {
     "expr": "tezos_metrics_chain_head_seed_nonce_revelation{namespace=~\"$namespace\",pod=~\"$workload.*\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}}: seed nonce revelation"
    },
    {
     "expr": "tezos_metrics_chain_head_reveal{namespace=~\"$namespace\",pod=~\"$workload.*\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}}: reveal"
    }
   ]
  },
  {
   "title": "Invalid blocks history",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 14 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "tezos_metrics_chain_invalid_blocks{namespace=~\"$namespace\",pod=~\"$workload.*\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "title": "Hardware stats", "type": "row", "gridPos": { "h": 0, "w": 8, "x": 0, "y": 22 } },
  {
   "title": "Cpu actitvity",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum by (pod) (rate(container_cpu_usage_seconds_total{namespace=~\"$namespace\",pod=~\"$workload.*\",pod=~\"$pod\"}[5m]))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "mbytes" }
   ],
   "targets": [
    {
     "expr": "sum by (pod) (container_memory_working_set_bytes{namespace=~\"$namespace\",pod=~\"$workload.*\",pod=~\"$pod\"})",
     "legendFormat": "{{pod}}: mem"
    },
    {
     "expr": "sum by (pod) (container_memory_swap{namespace=~\"$namespace\",pod=~\"$workload.*\",pod=~\"$pod\"})",
     "legendFormat": "{{pod}}: swap usage"
    }
   ]
  },
  {
   "title": "Disk free space",
   "type": "stat",
   "gridPos": { "h": 8, "w": 2, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filesystem_free_bytes{mountpoint=\"/\"}",
     "legendFormat": "Available bytes on disk."
    }
   ]
  },
  {
   "title": "Storage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 11, "x": 2, "y": 30 },
   "yaxes": [
    { "format": "mbytes" }
   ],
   "targets": [
    {
     "expr": "tezos_metrics_storage_total{namespace=~\"$namespace\",pod=~\"$workload.*\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}}: Total"
    },
    {
     "expr": "tezos_metrics_storage_context{namespace=~\"$namespace\",pod=~\"$workload.*\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}}: Context store"
    },
    {
     "expr": "tezos_metrics_storage_index{namespace=~\"$namespace\",pod=~\"$workload.*\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}}: Context index"
    },
    {
     "expr": "tezos_metrics_storage_store{namespace=~\"$namespace\",pod=~\"$workload.*\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}}: Store"
    }
   ]
  },
  {
   "title": "IOs",
   "type": "graph",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 30 },
   "yaxes": [
    { "format": "kbytes" }
   ],
   "targets": [
    {
     "expr": "netdata_apps_lreads_KiB_persec_average{dimension=\"tezos\"}",
     "legendFormat": "reads"
    },
    {
     "expr": "netdata_apps_lwrites_KiB_persec_average{dimension=\"tezos\"}",
     "legendFormat": "writes"
    }
   ]
  },
  {
   "title": "Network traffic",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{namespace=~\"$namespace\",pod=~\"$workload.*\",pod=~\"$pod\"}[5m]) > 0",
     "legendFormat": "Bytes received"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{namespace=~\"$namespace\",pod=~\"$workload.*\",pod=~\"$pod\"}[5m]) > 0",
     "legendFormat": "Bytes transmitted"
    }
   ]
  },
  {
   "title": "File descriptors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(netdata_apps_pipes_open_pipes_average{dimension=\"tezos\"}) + sum(netdata_apps_files_open_files_average{dimension=\"tezos\"}) + sum(netdata_apps_sockets_open_sockets_average{dimension=\"tezos\"})",
     "legendFormat": "All fds"
    },
    {
     "expr": "netdata_apps_sockets_open_sockets_average{dimension=\"tezos\"}",
     "legendFormat": "Sockets"
    },
    {
     "expr": "netdata_apps_files_open_files_average{dimension=\"tezos\"}",
     "legendFormat": "Files"
    },
    {
     "expr": "netdata_apps_pipes_open_pipes_average{dimension=\"tezos\"}",
     "legendFormat": "Pipes"
    }
   ]
  },
  { "title": "P2P stats", "type": "row", "gridPos": { "h": 0, "w": 8, "x": 0, "y": 46 } },
  {
   "title": "Mempool status",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 46 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "tezos_metrics_mempool_pending_applied{namespace=~\"$namespace\",pod=~\"$workload.*\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}}: Applied"
    },
    {
     "expr": "tezos_metrics_mempool_pending_refused{namespace=~\"$namespace\",pod=~\"$workload.*\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}}: Refused"
    },
    {
     "expr": "tezos_metrics_mempool_pending_branch_refused{namespace=~\"$namespace\",pod=~\"$workload.*\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}}: Branch refused"
    },
    {
     "expr": "tezos_metrics_mempool_pending_branch_delayed{namespace=~\"$namespace\",pod=~\"$workload.*\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}}: Branch applied"
    },
    {
     "expr": "tezos_metrics_mempool_pending_unprocessed{namespace=~\"$namespace\",pod=~\"$workload.*\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}}: Unprocessed"
    }
   ]
  },
  {
   "title": "P2P total connections",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 46 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "tezos_metrics_p2p_connections_total{namespace=~\"$namespace\",pod=~\"$workload.*\",pod=~\"$pod\"} - tezos_metrics_p2p_connections_incoming{namespace=~\"$namespace\",pod=~\"$workload.*\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}}: outgoing"
    },
    {
     "expr": "tezos_metrics_p2p_connections_incoming{namespace=~\"$namespace\",pod=~\"$workload.*\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}}: incoming"
    }
   ]
  },
  {
   "title": "P2P peers connections",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 54 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "tezos_metrics_p2p_peers_disconnected{namespace=~\"$namespace\",pod=~\"$workload.*\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}}: Disconnected peers"
    },
    {
     "expr": "tezos_metrics_p2p_peers_running{namespace=~\"$namespace\",pod=~\"$workload.*\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}}: Running peers"
    },
    {
     "expr": "tezos_metrics_p2p_points_greylisted{namespace=~\"$namespace\",pod=~\"$workload.*\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}}: Waiting to reconnect"
    }
   ]
  },
  {
   "title": "P2P points connections",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 54 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "tezos_metrics_p2p_points_disconnected{namespace=~\"$namespace\",pod=~\"$workload.*\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}}: Disconnected points"
    },
    {
     "expr": "tezos_metrics_p2p_points_running{namespace=~\"$namespace\",pod=~\"$workload.*\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}}: Running points"
    }
   ]
  },
  { "title": "Workers stats", "type": "row", "gridPos": { "h": 0, "w": 8, "x": 0, "y": 62 } },
  {
   "title": "Pending workers requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 62 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "tezos_metrics_stats_block_validator_pending_requests{namespace=~\"$namespace\",pod=~\"$workload.*\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}}: Block validator"
    },
    {
     "expr": "tezos_metrics_stats_main_chain_prevalidators_pending_requests{namespace=~\"$namespace\",pod=~\"$workload.*\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}}: Chain prevalidator"
    },
    {
     "expr": "tezos_metrics_stats_main_chain_validators_pending_requests{namespace=~\"$namespace\",pod=~\"$workload.*\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}}: Chain validators"
    }
   ]
  },
  {
   "title": "DDB Workers",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 62 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "tezos_metrics_stats_main_chain_validators_ddb_block_header_db_table_length{namespace=~\"$namespace\",pod=~\"$workload.*\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}}: headers table"
    },
    {
     "expr": "tezos_metrics_stats_main_chain_validators_ddb_block_header_db_scheduler_length{namespace=~\"$namespace\",pod=~\"$workload.*\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}}: headers scheduler"
    },
    {
     "expr": "tezos_metrics_stats_main_chain_validators_ddb_operations_db_table_length{namespace=~\"$namespace\",pod=~\"$workload.*\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}}: operations table"
    },
    {
     "expr": "tezos_metrics_stats_main_chain_validators_ddb_operations_db_scheduler_length{namespace=~\"$namespace\",pod=~\"$workload.*\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}}: operations scheduler"
    },
    {
     "expr": "tezos_metrics_stats_main_chain_validators_ddb_operation_db_table_length{namespace=~\"$namespace\",pod=~\"$workload.*\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}}: operation table"
    },
    {
     "expr": "tezos_metrics_stats_main_chain_validators_ddb_operation_db_scheduler_length{namespace=~\"$namespace\",pod=~\"$workload.*\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}}: operation scheduler"
    }
   ]
  },
  {
   "title": "Main chain prevalidators workers",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 70 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "tezos_metrics_stats_main_chain_prevalidators_workers_closed{namespace=~\"$namespace\",pod=~\"$workload.*\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}}: closed"
    },
    {
     "expr": "tezos_metrics_stats_main_chain_prevalidators_workers_closing{namespace=~\"$namespace\",pod=~\"$workload.*\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}}: closing"
    },
    {
     "expr": "tezos_metrics_stats_main_chain_prevalidators_workers_launching{namespace=~\"$namespace\",pod=~\"$workload.*\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}}: launching"
    },
    {
     "expr": "tezos_metrics_stats_main_chain_prevalidators_workers_running{namespace=~\"$namespace\",pod=~\"$workload.*\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}}: running"
    }
   ]
  },
  {
   "title": "Main chain peer validators workers",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 70 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "tezos_metrics_stats_main_chain_validators_peer_validators_closed{namespace=~\"$namespace\",pod=~\"$workload.*\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}}: closed"
    },
    {
     "expr": "tezos_metrics_stats_main_chain_validators_peer_validators_closing{namespace=~\"$namespace\",pod=~\"$workload.*\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}}: closing"
    },
    {
     "expr": "tezos_metrics_stats_main_chain_validators_peer_validators_launching{namespace=~\"$namespace\",pod=~\"$workload.*\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}}: launching"
    },
    {
     "expr": "tezos_metrics_stats_main_chain_validators_peer_validators_running{namespace=~\"$namespace\",pod=~\"$workload.*\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}}: running"
    }
   ]
  },
  {
   "title": "Peer validators fetched block pipelines",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 78 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "tezos_metrics_stats_main_chain_validators_peer_validators_fetched_block_avg{namespace=~\"$namespace\",pod=~\"$workload.*\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}}: fetched blocks avg"
    },
    {
     "expr": "tezos_metrics_stats_main_chain_validators_peer_validators_fetched_block_max{namespace=~\"$namespace\",pod=~\"$workload.*\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}}: fetched blocks max"
    },
    {
     "expr": "tezos_metrics_stats_main_chain_validators_peer_validators_fetched_block_min{namespace=~\"$namespace\",pod=~\"$workload.*\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}}: fetched blocks min"
    }
   ]
  },
  {
   "title": "Peer validators fetched header pipelines",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 78 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "tezos_metrics_stats_main_chain_validators_peer_validators_fetched_block_avg{namespace=~\"$namespace\",pod=~\"$workload.*\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}}: fetched blocks avg"
    },
    {
     "expr": "tezos_metrics_stats_main_chain_validators_peer_validators_fetched_block_max{namespace=~\"$namespace\",pod=~\"$workload.*\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}}: fetched blocks max"
    },
    {
     "expr": "tezos_metrics_stats_main_chain_validators_peer_validators_fetched_block_min{namespace=~\"$namespace\",pod=~\"$workload.*\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}}: fetched blocks min"
    }
   ]
  },
  { "title": "Miscellaneous", "type": "row", "gridPos": { "h": 0, "w": 8, "x": 0, "y": 86 } },
  {
   "title": "GC maintenance operations",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 86 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "ocaml_gc_minor_collections{namespace=~\"$namespace\",pod=~\"$workload.*\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}}: Minor collections"
    },
    {
     "expr": "ocaml_gc_major_collections{namespace=~\"$namespace\",pod=~\"$workload.*\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}}: Major collections"
    },
    {
     "expr": "ocaml_gc_major_compactions{namespace=~\"$namespace\",pod=~\"$workload.*\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}}: Heap compactions"
    }
   ]
  },
  {
   "title": "GC minor and major word sizes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 86 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "ocaml_gc_heap_words{namespace=~\"$namespace\",pod=~\"$workload.*\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}}: Major heap"
    },
    {
     "expr": "ocaml_gc_top_heap_words{namespace=~\"$namespace\",pod=~\"$workload.*\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}}: Top major heap"
    }
   ]
  }
 ]
}