name: Preview
on:
  pull_request:
    branches:
      - main
jobs:
  preview:
    name: Preview
    # don't do this on fork - this won't work because secrets won't be accessible
    if: github.event.pull_request.head.repo.full_name == github.repository
    uses: ./.github/workflows/setup.yml
    secrets: inherit
    with:
      pulumi-command: preview

  validate-yaml:
    name: Validate YAML Files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Validate YAML Files
        run: |
          python -c "import yaml, glob; [yaml.safe_load(open(file)) for file in glob.glob('networks/*/*.yaml')]"
